version: '3'

services:
  extractor:
    image: multimoml/extractor:latest
    container_name: extractor
    restart: unless-stopped
    networks:
      - products-db
      - traefik-proxy
    environment: 
      # Mongo
      M_USERNAME: ${M_USERNAME}
      M_PASSWORD: ${M_PASSWORD}
      DATABASE: ${DATABASE}
      # Extractor
      ENVIRONMENT: "prod"
      M_SERVER: products-db:27017
      RUN_INTERVAL: 14400 # 4h in seconds
      PORT: 6000
    labels:
      traefik.enable: true
      traefik.docker.network: traefik-proxy # needed if you have multiple networks and no default
      traefik.http.routers.extractor.rule: Host(`${DOMAIN}`) && PathPrefix(`/extractor/`)
      traefik.http.routers.extractor.entrypoints: https
      traefik.http.services.extractor.loadbalancer.server.port: 6000
    depends_on:
      - products-db
    
  products-db:
    image: docker.io/mongo:latest
    container_name: products-db
    restart: unless-stopped
    networks:
      - products-db
    ports:
      - 27017:27017
    volumes:
      - /etc/multimo/docker-data/products-db:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${M_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${M_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE}
  
  products-db-ui:
    image: docker.io/mongo-express:latest
    container_name: products-db-ui
    restart: unless-stopped
    networks:
      - products-db
      - traefik-proxy
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${M_USERNAME}:${M_PASSWORD}@products-db:27017/ #${DATABASE}
    labels:
      traefik.enable: true
      traefik.docker.network: traefik-proxy # needed if you have multiple networks and no default
      traefik.http.routers.products-db-ui.rule: Host(`products-db-ui.${DOMAIN}`)
      traefik.http.routers.products-db-ui.entrypoints: https
      traefik.http.services.products-db-ui.loadbalancer.server.port: 8081
      traefik.http.routers.products-db-ui.middlewares: traefik-auth
    depends_on:
      - products-db

networks:
  products-db:
    external: true
  traefik-proxy:
    external: true