version: '3'

services:
  #myapplication:
  #  image: myapp:1.0
  #  environment: 
  #    - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
  #  ports:
  #    - 3000:3000
    
  extractor-timer-mongo:
    image: docker.io/mongo:latest
    container_name: extractor-timer-mongo
    restart: unless-stopped
    networks:
      - extractor-timer
    ports:
      - 27017:27017
    volumes:
      - /etc/multimo/extractor-timer/mongo-data:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${M_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${M_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE}
  
  extractor-timer-mongo-express:
    image: docker.io/mongo-express:latest
    container_name: extractor-timer-mongo-express
    restart: unless-stopped
    networks:
      - extractor-timer
      - traefik-proxy
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${M_USERNAME}:${M_PASSWORD}@extractor-timer-mongo:27017/ #${DATABASE}
    labels:
      traefik.enable: false
      traefik.http.routers.extractor-timer-mongo-express.rule: Host(`extractor-timer-mongo-express.${DOMAIN}`)
      traefik.http.routers.extractor-timer-mongo-express.entrypoints: https
      traefik.http.services.extractor-timer-mongo-express.loadbalancer.server.port: 8081
    depends_on:
      - extractor-timer-mongo

networks:
  extractor-timer:
  traefik-proxy:
    external: true