// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/extract": {
            "post": {
                "description": "Initiate extraction",
                "tags": [
                    "Extract"
                ],
                "summary": "Initiate extraction",
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": ""
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Get extractors internal state",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Get internal state",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": ""
                        }
                    }
                }
            }
        },
        "/self": {
            "get": {
                "description": "Get liveness ad readiness status of the microservice",
                "tags": [
                    "Kubernetes"
                ],
                "summary": "Get liveness and readiness status of the microservice",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": ""
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": ""
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:6000",
	BasePath:         "/extractor",
	Schemes:          []string{},
	Title:            "Extractor API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
